version: '3'
services:
    api:
      build:
        context: .
        dockerfile: ./dockers/Dockerfile
      container_name: api_teste
      command: python manage.py runserver 0.0.0.0:8080
      env_file:
        - ./envs/api.env
      volumes:
        - ./source:/source
      ports:
        - 8160:8080
      depends_on:
        - postgres

    postgres:
      image: postgres:9.6
      container_name: prd-db-postgres-9.6
      restart: unless-stopped
      volumes:
        - ./postgres:/var/lib/postgresql/data
        - ./envs:/docker-entrypoint-initdb.d
      env_file:
        - ./envs/postgres.env
      ports:
        - 4040:5432

