# Generated by Django 2.2.7 on 2019-11-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DurationField(verbose_name='Minutos')),
                ('criado', models.TimeField(auto_now_add=True, verbose_name='Criado')),
                ('paid', models.BooleanField(default=False, verbose_name='Pagamento')),
                ('left', models.BooleanField(default=False, verbose_name='Canhoto')),
                ('plate', models.CharField(max_length=7, verbose_name='Placa')),
            ],
        ),
    ]
