# Generated by Django 2.2.7 on 2019-11-26 20:45

from django.db import migrations, models
import estacionamento.validators


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='plate',
            field=models.CharField(max_length=8, validators=[estacionamento.validators.placa], verbose_name='Placa'),
        ),
    ]
