# Generated by Django 2.2.7 on 2019-11-29 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamento', '0004_auto_20191128_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='criado',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado'),
        ),
        migrations.AlterField(
            model_name='carro',
            name='saida',
            field=models.DateTimeField(default='0000-00-00T00:00:00.000000Z', verbose_name='Saida'),
        ),
        migrations.AlterField(
            model_name='carro',
            name='time',
            field=models.CharField(default='0 minutos', max_length=12, verbose_name='Minutos'),
        ),
    ]
