# Generated by Django 2.2.7 on 2019-11-29 12:42

from django.db import migrations, models
import estacionamento.models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamento', '0006_auto_20191128_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='criado',
            field=models.DateTimeField(default=estacionamento.models.get_date, verbose_name='Criado'),
        ),
    ]
