# Generated by Django 2.2.8 on 2019-12-03 01:34

from django.db import migrations, models
import estacionamento.models
import estacionamento.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(default='0 minutos', max_length=21, verbose_name='Minutos')),
                ('criado', models.DateTimeField(default=estacionamento.models.get_date, verbose_name='Criado')),
                ('paid', models.BooleanField(default=False, verbose_name='Pagamento')),
                ('saida', models.DateTimeField(default='2019-01-01T00:00:00.000000Z', verbose_name='Saida')),
                ('left', models.BooleanField(default=False, verbose_name='Canhoto')),
                ('plate', models.CharField(max_length=8, validators=[estacionamento.validators.placa], verbose_name='Placa')),
            ],
        ),
    ]
