# Generated by Django 2.2.7 on 2019-11-29 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamento', '0003_carro_saida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='saida',
            field=models.TimeField(verbose_name='Saida'),
        ),
    ]
