# Generated by Django 2.2.7 on 2019-11-29 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamento', '0005_auto_20191128_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='saida',
            field=models.DateTimeField(default='2019-01-01T00:00:00.000000Z', verbose_name='Saida'),
        ),
    ]
